# Site settings
title:       bumble mumble
email:       
author:      bumbleborn
description: "games and articles from bumbleborn."
# baseurl:     /bumbleblog
url:         "https://bumblemumble.com"
image_path:  /assets/images/
date_format: "%-d %b, %Y"
header_pages:
 - about.md

# defaults
defaults:
 -
  scope:
    path: ""
    type: "posts"
  values:
      layout: "post"
      permalink: /blog/:title/
      color: red

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics:
google_tag_manager:
# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    true
ajaxify_contact_form: false
enable_mathjax: false
extended_fonts: false
enable_anchorjs: false
# Preview image for social media aka og:image and twitter:image
post_preview_image: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname:

# Social icons
github_username:
reddit_username:
twitter_username: bumbleborn

text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    pretty
paginate:     4
sass:
  style: compressed
plugins:
  - jekyll-paginate
  - jekyll-sitemap
# https://github.com/jekyll/jekyll/issues/2938
exclude:
  - Gemfile
  - Gemfile.lock
  - Rakefile
  - README.md
  - screenshot.png
  - vendor
